/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import java.util.List;
import model.Movie;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ShowlistmovieForm extends javax.swing.JPanel {
    /**
     * Creates new form ShowlistmovieForm
     */
    public ShowlistmovieForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        paneAction = new javax.swing.JPanel();
        btnAddMovie = new javax.swing.JButton();
        editMovie = new javax.swing.JButton();
        deleteMovie = new javax.swing.JButton();
        tableMovies = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(panelHeader, java.awt.BorderLayout.PAGE_START);

        btnAddMovie.setText("Thêm Phim");
        btnAddMovie.addActionListener(this::btnAddMovieActionPerformed);

        editMovie.setText("Sửa ");

        deleteMovie.setText("Xóa");

        javax.swing.GroupLayout paneActionLayout = new javax.swing.GroupLayout(paneAction);
        paneAction.setLayout(paneActionLayout);
        paneActionLayout.setHorizontalGroup(
            paneActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnAddMovie)
                .addGap(126, 126, 126)
                .addComponent(editMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(deleteMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        paneActionLayout.setVerticalGroup(
            paneActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActionLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(paneActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMovie)
                    .addComponent(editMovie)
                    .addComponent(deleteMovie))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(paneAction, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phim", "Tên Phim", "Mô tả", "Đạo diễn", "Thời lương", "Ngày công chiếu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMovies.setViewportView(jTable1);

        add(tableMovies, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMovieActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

    }//GEN-LAST:event_btnSearchActionPerformed

    // --- CÁC HÀM GETTER ĐỂ CONTROLLER LẤY GIAO DIỆN XỬ LÝ ---
    public javax.swing.JButton getBtnSearch() {
        return btnSearch;
    }

    public javax.swing.JTextField getTxtSearch() {
        return txtSearch;
    }

    public javax.swing.JTable getTableMovies() {
        return jTable1;
    }
    public javax.swing.JButton getBtnAddMovie() {
        return btnAddMovie;
    }

    public javax.swing.JButton getEditMovie() {
        return editMovie;
    }

    public javax.swing.JButton getDeleteMovie() {
        return deleteMovie;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMovie;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton deleteMovie;
    private javax.swing.JButton editMovie;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel paneAction;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JScrollPane tableMovies;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}

