/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ADMIN
 */
public class show_time_room_infrForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(show_time_room_infrForm.class.getName());

    /**
     * Creates new form show_time_room_infrForm
     */
    public show_time_room_infrForm() {
        initComponents();
        setLocationRelativeTo(null); // Hiện ra giữa màn hình
        setupUIDesign();
        // ĐÁNH THỨC CONTROLLER ĐỂ NÓ KHÓA Ô NHẬP VÀ XỬ LÝ NÚT BẤM
        new controller.RoomManagerController(this);
    }
    public javax.swing.JButton getBtnBack() {
        return backtodashboard;
    }
    private void setupUIDesign() {
        // 1. Đổi màu nền của toàn bộ Form thành Trắng (#FFFFFF)
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        
        // 2. Định nghĩa Font chữ (Segoe UI, size 14) và Màu chữ thường (#333333)
        java.awt.Font mainFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14);
        java.awt.Color textColor = new java.awt.Color(51, 51, 51); 

        // Áp dụng Font và Màu chữ cho các Tiêu đề (Label) - Bạn điền tên các biến Label của bạn vào đây
        javax.swing.JLabel[] labels = {jLabel1, jLabel2, jLabel3};
        for (javax.swing.JLabel lbl : labels) {
            lbl.setFont(mainFont);
            lbl.setForeground(textColor);
        }

        // 3. Định nghĩa thiết kế cho Nút bấm (Màu Cam #FF6600, Chữ Trắng, In đậm)
        java.awt.Font btnFont = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);
        java.awt.Color btnBgColor = new java.awt.Color(255, 102, 0); // #FF6600
        java.awt.Color btnTextColor = new java.awt.Color(255, 255, 255); // #FFFFFF

        // Gom các nút bấm vào 1 mảng để set màu cùng lúc
        // Lưu ý: Sửa lại tên btnAdd, btnDelete... cho khớp với tên biến bạn đặt
        javax.swing.JButton[] buttons = {btnAddRoom, backtodashboard};
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(btnFont);
            btn.setBackground(btnBgColor);
            btn.setForeground(btnTextColor);
            
            // 2 Dòng này CỰC KỲ QUAN TRỌNG trong Java Swing để nút hiển thị đúng màu nền trên Windows
            btn.setOpaque(true);
            btn.setBorderPainted(false);
            
            // Đổi con trỏ chuột thành hình bàn tay khi di chuột vào nút
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
        javax.swing.table.JTableHeader header = tblRooms.getTableHeader(); // Đã sửa thành tblRooms
        
        // Khóa cứng cột, không cho kéo thả nhảy lung tung
        header.setReorderingAllowed(false);
        
        // Set màu chữ Trắng và Font in đậm
        header.setForeground(new java.awt.Color(255, 255, 255)); 
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)); 
        
        // Set màu nền Cam (#FF6600)
        header.setBackground(new java.awt.Color(255, 102, 0)); 
        
        // Ép hệ điều hành Windows hiển thị màu nền của Header
        ((javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer()).setBackground(new java.awt.Color(255, 102, 0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        txtRoomId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRoomName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalSeats = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnAddRoom = new javax.swing.JButton();
        backtodashboard = new javax.swing.JButton();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinema System - Quản lý Phòng & Lịch Chiếu");

        txtRoomId.addActionListener(this::txtRoomIdActionPerformed);

        jLabel1.setText("Mã phòng:");

        jLabel2.setText("Tên phòng: ");

        txtRoomName.addActionListener(this::txtRoomNameActionPerformed);

        jLabel3.setText("Tổng số ghế:");

        txtTotalSeats.addActionListener(this::txtTotalSeatsActionPerformed);

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Tổng Số Ghế(Tối đa 50 ghế)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRooms);

        btnAddRoom.setText("Thêm Phòng & Sinh Ghế");
        btnAddRoom.addActionListener(this::btnAddRoomActionPerformed);

        backtodashboard.setText("Back ");
        backtodashboard.addActionListener(this::backtodashboardActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRoomId))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                                    .addComponent(txtRoomName, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                                    .addComponent(txtTotalSeats)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(backtodashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoomName, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnAddRoom)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(backtodashboard)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoomIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomIdActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void txtRoomNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNameActionPerformed

    private void txtTotalSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalSeatsActionPerformed

    private void backtodashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtodashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backtodashboardActionPerformed

    public javax.swing.JButton getBtnAddRoom() {
        return btnAddRoom;
    }

    public javax.swing.JTextField getTxtRoomId() {
        return txtRoomId;
    }

    public javax.swing.JTextField getTxtRoomName() {
        return txtRoomName;
    }

    public javax.swing.JTextField getTxtTotalSeats() {
        return txtTotalSeats;
    }

    public javax.swing.JTable getTblRooms() {
        return tblRooms;
    }
    public void clearInputFields() {
        txtRoomId.setText("");
        txtRoomName.setText("");
        txtTotalSeats.setText("");
        txtRoomId.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtodashboard;
    private javax.swing.JButton btnAddRoom;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTextField txtRoomId;
    private javax.swing.JTextField txtRoomName;
    private javax.swing.JTextField txtTotalSeats;
    // End of variables declaration//GEN-END:variables
}